# Form implementation generated from reading ui file 'dialog_form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1130, 727)
        Dialog.setMinimumSize(QtCore.QSize(914, 549))
        Dialog.setMaximumSize(QtCore.QSize(100000, 100000))
        self.nameOfTheFloor = QtWidgets.QLabel(parent=Dialog)
        self.nameOfTheFloor.setGeometry(QtCore.QRect(520, 0, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nameOfTheFloor.setFont(font)
        self.nameOfTheFloor.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.nameOfTheFloor.setText("")
        self.nameOfTheFloor.setObjectName("nameOfTheFloor")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 1091, 661))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Floor plan"))
