# Form implementation generated from reading ui file 'dialog_form_3.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(734, 514)
        Dialog.setMinimumSize(QtCore.QSize(734, 514))
        Dialog.setMaximumSize(QtCore.QSize(734, 514))
        self.label_date = QtWidgets.QLabel(parent=Dialog)
        self.label_date.setGeometry(QtCore.QRect(220, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 691, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Замены"))
        self.label_date.setText(_translate("Dialog", "Замены уроков на"))
