# Form implementation generated from reading ui file 'dialog_form_5.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 124)
        self.password = QtWidgets.QLineEdit(parent=Dialog)
        self.password.setGeometry(QtCore.QRect(70, 40, 201, 21))
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(parent=Dialog)
        self.ok_button.setGeometry(QtCore.QRect(30, 80, 91, 31))
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(160, 80, 91, 31))
        self.cancel_button.setObjectName("cancel_button")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 221, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление замены"))
        self.label.setText(_translate("Dialog", "Пароль:"))
        self.ok_button.setText(_translate("Dialog", "Ок"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
